let suggestions = [
    "Tenis ",
    "Calça",
    "Camiseta",
    "Blusa",
    "Bermuda moletom",
    "Blusa de frio",
    "Moletom",
    "Nike",
    "Adidas",
    "Oculos",
    "Luvas",
    "Relógio",
    "Short",
    "Meias",
    "Configurações",
    "Login",
    "Cadastrar",
    "Alterar dados",
    "Home",
    "Calçados",
    "Toucas",
    "Bonés",
    "Shoulder bag",
    "High",
    "Sufgang",
    "Chuteira",
    "roupa",
];