-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 15:28:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sendstyle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sendstyle
-- -----------------------------------------------------
DROP DATABASE if exists sendstyle;

CREATE SCHEMA IF NOT EXISTS `sendstyle` DEFAULT CHARACTER SET utf8 ;
USE `sendstyle` ;

-- -----------------------------------------------------
-- Table `sendstyle`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sendstyle`.`usuario` (
    `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(60) NULL DEFAULT NULL,
    `telefone` VARCHAR(45) NULL DEFAULT NULL,
    `email` VARCHAR(45) NULL DEFAULT NULL,
    `senha` VARCHAR(45) NULL DEFAULT NULL,
    `estado` VARCHAR(45) NULL,
    `cidade` VARCHAR(45) NULL,
    `perfil` VARCHAR(45) NULL DEFAULT 'Usuário',
    `isAdmin` int(1) DEFAULT NULL,
     `situacao` VARCHAR(45) NULL DEFAULT 'Ativo' COMMENT 'Ativo\ninativo\nbloqueado',
    PRIMARY KEY (`idUsuario`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4;

insert into usuario (`nome`,`telefone`,`email`,`senha`,`estado`,`cidade`,`perfil`,`isAdmin`)
Values ('Adm','6145454545','adm@gmail.com',md5('123123'),'Distrito Federal','Brasília','Administrador',true);

-- -----------------------------------------------------
-- Table `sendstyle`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sendstyle`.`avaliacoes` (
    `idAvaliacao` INT(11) NOT NULL AUTO_INCREMENT,
    `textoAvaliacao` VARCHAR(45) NULL DEFAULT NULL,
    `notaAvaliacao` INT(11) NULL DEFAULT NULL,
    `idUsuario` INT(11) NOT NULL,
    PRIMARY KEY (`idAvaliacao`, `idUsuario`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sendstyle`.`anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sendstyle`.`anuncio` (
    `idAnuncio` INT(11) NOT NULL AUTO_INCREMENT,
    `nomeAnuncio` VARCHAR(45) NULL DEFAULT NULL,
    `valorAnuncio` FLOAT NULL DEFAULT NULL,
    `imagem_produto` TEXT NULL,
    `avaliacoesAnuncio` VARCHAR(45) NULL DEFAULT NULL,
    `tamanho` VARCHAR(45) NULL DEFAULT NULL,
    `cores` VARCHAR(45) NULL DEFAULT NULL,
    `descAnuncio` VARCHAR(45) NULL DEFAULT NULL,
    `idAvaliacao` INT(11) NOT NULL,
    `idUsuario` INT(11) NOT NULL,
    PRIMARY KEY (`idAnuncio`, `idAvaliacao`, `idUsuario`),
    INDEX `fk_Anuncios_Avaliacoes1_idx` (`idAvaliacao` ASC),
    INDEX `fk_Anuncios_Anunciante1_idx` (`idUsuario` ASC),
    CONSTRAINT `fk_Anuncios_Anunciante1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sendstyle`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Anuncios_Avaliacoes1`
    FOREIGN KEY (`idAvaliacao`)
    REFERENCES `sendstyle`.`avaliacoes` (`idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sendstyle`.`mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sendstyle`.`mensagem` (
    `idMensagem` INT(11) NOT NULL AUTO_INCREMENT,
    `textoMensagem` VARCHAR(45) NULL DEFAULT NULL,
    `nomeMensagem` VARCHAR(45) NULL DEFAULT NULL,
    `enderecoMensagem` VARCHAR(45) NULL DEFAULT NULL,
    `dataMensagem` DATE NULL DEFAULT NULL,
    `horaMensagem` INT(11) NULL DEFAULT NULL,
    `idAnuncio` INT(11) NOT NULL,
    `idAvaliacao` INT(11) NOT NULL,
    `idUsuario` INT(11) NOT NULL,
    PRIMARY KEY (`idMensagem`, `idAnuncio`, `idAvaliacao`, `idUsuario`),
    INDEX `fk_Mensagem_Anuncios1_idx` (`idAnuncio` ASC, `idAvaliacao` ASC),
    CONSTRAINT `fk_Mensagem_Anuncios1`
    FOREIGN KEY (`idAnuncio` , `idAvaliacao`)
    REFERENCES `sendstyle`.`anuncio` (`idAnuncio` , `idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
